"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
var React = require("react");
var react_1 = require("react");
var custom_input_component_1 = require("../../components/custom-input/custom-input.component");
function Process_Page(_a) {
    var handleChange = _a.handleChange;
    var _b = (0, react_1.useState)(false), ToggelValue = _b[0], setToggelValue = _b[1];
    console.log("toggel Value", ToggelValue);
    return (React.createElement(React.Fragment, null,
        React.createElement("div", { className: "main card firstDiv" },
            React.createElement("div", { className: "text-center card-title col-12", style: { textAlign: "start", backgroundColor: "#8389d4" } },
                React.createElement("span", { className: "row-header p-0 m-0" }, "Add Process Master")),
            React.createElement("form", { className: "row-content form col-sm-12 pt-0" },
                React.createElement("fieldset", { className: "form-group border p-0" },
                    React.createElement("legend", { className: "px-2", "aria-expanded": "true", style: { fontSize: "1.1rem", cursor: "pointer" } },
                        React.createElement("svg", { className: "ml-1", style: { width: "15px" }, xmlns: "http://www.w3.org/2000/svg", viewBox: "0 0 448 512" },
                            React.createElement("path", { d: "M384 32H64C28.65 32 0 60.65 0 96v320c0 35.34 28.65 64 64 64h320c35.35 0 64-28.66 64-64V96C448 60.65 419.3 32 384 32zM345.6 232.3l-104 112C237 349.2 230.7 352 224 352s-13.03-2.781-17.59-7.656l-104-112c-6.5-7-8.219-17.19-4.407-25.94C101.8 197.7 110.5 192 120 192h208c9.531 0 18.19 5.656 21.1 14.41C353.8 215.2 352.1 225.3 345.6 232.3z" }))),
                    React.createElement(React.Fragment, null,
                        React.createElement("span", { className: "d-flex section2 col-sm-12" },
                            React.createElement(custom_input_component_1.default, { name: "Process", classCategory: "form-control inp mb-2 Process", ipType: "text", label: "Process", ipTitle: "Enter Process", dataArray: [] }),
                            React.createElement(custom_input_component_1.default, { name: "ProcessFloor", classCategory: "form-control inp mb-2 ProcessFloor", ipType: "text", label: "Process Floor", ipTitle: "Enter Process Floor", dataArray: [] }),
                            React.createElement(custom_input_component_1.default, { name: "ClipBoard", classCategory: "form-control inp mb-2 ClipBoard", ipType: "text", label: "P Srno For ClipBoard", ipTitle: "Enter ClipBoard", dataArray: [] })),
                        React.createElement("span", { className: "d-flex section2 col-sm-12" },
                            React.createElement(custom_input_component_1.default, { name: "DebitorAccount", classCategory: "form-control inp mb-2 DebitorAccount", ipType: "text", label: "Debitor Account", ipTitle: "Enter Debitor Account", dataArray: [] }),
                            React.createElement(custom_input_component_1.default, { name: "AddJobWork", classCategory: "form-control inp mb-2 AddJobWork", ipType: "text", label: "Add JobWork chrgs.", ipTitle: "Enter Add JobWork chrgs.", dataArray: [] }),
                            React.createElement(custom_input_component_1.default, { name: "Tollerance", classCategory: "form-control inp mb-2 Tollerance", ipType: "number", label: "Tollerance (%)", ipTitle: "Enter Tollerance", dataArray: [] })),
                        React.createElement("span", { className: "d-flex section2 col-sm-12" },
                            React.createElement(custom_input_component_1.default, { name: "OverHead", classCategory: "form-control inp mb-2 OverHead", ipType: "number", label: "OverHead (%)", ipTitle: "Enter OverHead", dataArray: [] }),
                            React.createElement(custom_input_component_1.default, { name: "Material Req", classCategory: "form-control inp mb-2 MaterialReq", ipType: "text", label: "Material Req. before Days", ipTitle: "Enter Material Req. before Days", dataArray: [] }),
                            React.createElement(custom_input_component_1.default, { name: "Process Group No", classCategory: "form-control inp mb-2 MaterialReq", ipType: "text", label: "Process Group No", ipTitle: "Enter Process Group No", dataArray: [] })),
                        React.createElement("span", { className: "d-flex section2 col-sm-12" },
                            React.createElement(custom_input_component_1.default, { name: "PlanHours", classCategory: "form-control inp mb-2 PlanHours", ipType: "number", label: "Plan Hours Per Day", ipTitle: "Enter Plan Hours Per Day", dataArray: [] }),
                            React.createElement(custom_input_component_1.default, { name: "Before Days", classCategory: "form-control inp mb-2 BeforeDays", ipType: "text", label: "Before Days", ipTitle: "Enter Before Days", dataArray: [] }))),
                    React.createElement("div", { className: "col-4" }))),
            React.createElement("span", { className: "row-content col-sm-12 pt-0" },
                React.createElement("fieldset", { className: "form-group border p-0" },
                    React.createElement("legend", { className: "px-2", "data-toggle": "collapse", "data-target": "#Switch", "aria-expanded": "true", "aria-controls": "Switch", style: { fontSize: "1.1rem", cursor: "pointer" } },
                        React.createElement("svg", { className: "ml-1", style: { width: "15px" }, xmlns: "http://www.w3.org/2000/svg", viewBox: "0 0 448 512" },
                            React.createElement("path", { d: "M384 32H64C28.65 32 0 60.65 0 96v320c0 35.34 28.65 64 64 64h320c35.35 0 64-28.66 64-64V96C448 60.65 419.3 32 384 32zM345.6 232.3l-104 112C237 349.2 230.7 352 224 352s-13.03-2.781-17.59-7.656l-104-112c-6.5-7-8.219-17.19-4.407-25.94C101.8 197.7 110.5 192 120 192h208c9.531 0 18.19 5.656 21.1 14.41C353.8 215.2 352.1 225.3 345.6 232.3z" }))),
                    React.createElement("div", { className: "show", id: "Switch" },
                        React.createElement("span", { className: "d-flex justify-content-between section2 col-sm-12" },
                            React.createElement("label", { htmlFor: "Consumption Not", style: { fontSize: "0.8em" }, className: "form-label labl labl2" }, "For Job Work"),
                            React.createElement("input", { type: "checkbox", onBlur: handleChange, className: "form-control custom-control-input col-3 InventoryDet", name: "", id: "", style: { cursor: 'pointer' } }),
                            React.createElement("label", { htmlFor: "Accounting Posting", style: { fontSize: "0.8em" }, className: "form-label labl labl2" }, "Is Accounting Posting"),
                            React.createElement("input", { type: "checkbox", onBlur: handleChange, className: "form-control custom-control-input col-3 InventoryDet", name: "", id: "", style: { cursor: 'pointer' } }),
                            React.createElement("label", { htmlFor: "Produce Qty", style: { fontSize: "0.8em" }, className: "form-label labl labl2" }, "Produce Qty is Greater then Paln Qty"),
                            React.createElement("input", { type: "checkbox", onBlur: handleChange, className: "form-control custom-control-input col-3 InventoryDet", name: "", id: "", style: { cursor: 'pointer' } }),
                            React.createElement("label", { htmlFor: "Produce Qty", style: { fontSize: "0.8em" }, className: "form-label labl labl2" }, "Change Consume Item Quantity"),
                            React.createElement("input", { type: "checkbox", onBlur: handleChange, className: "form-control custom-control-input col-3 InventoryDet", name: "", id: "", style: { cursor: 'pointer' } })),
                        React.createElement("span", { className: "d-flex justify-content-between section2 col-sm-12" },
                            React.createElement("label", { htmlFor: " IsConsumeQty", style: { fontSize: "0.8em" }, className: "form-label labl labl2" }, "Is Consume Qty Less than Req. Qty"),
                            React.createElement("input", { type: "checkbox", onBlur: handleChange, className: "form-control custom-control-input col-3 InventoryDet", name: "", id: "", style: { cursor: 'pointer' } }),
                            React.createElement("label", { htmlFor: " IsConsumeQtyZero", style: { fontSize: "0.8em" }, className: "form-label labl labl2" }, "Is Consume Qty Zero"),
                            React.createElement("input", { type: "checkbox", onBlur: handleChange, className: "form-control custom-control-input col-3 InventoryDet", name: "", id: "", style: { cursor: 'pointer' } }),
                            React.createElement("label", { htmlFor: " Mold Req.", style: { fontSize: "0.8em" }, className: "form-label labl labl2" }, "Mold Req."),
                            React.createElement("input", { type: "checkbox", onBlur: handleChange, className: "form-control custom-control-input col-3 InventoryDet", name: "", id: "", style: { cursor: 'pointer' } }),
                            React.createElement("label", { htmlFor: "Minus Stock", style: { fontSize: "0.8em" }, className: "form-label labl labl2" }, "Minus Stock Qty in Req."),
                            React.createElement("input", { type: "checkbox", onBlur: handleChange, className: "form-control custom-control-input col-3 InventoryDet", name: "", id: "", style: { cursor: 'pointer' } })),
                        React.createElement("span", { className: "d-flex justify-content-between section2 col-sm-12" },
                            React.createElement("label", { htmlFor: " Add New Cons", style: { fontSize: "0.8em" }, className: "form-label labl labl2" }, "Add New Cons. Item at Production"),
                            React.createElement("input", { type: "checkbox", onBlur: handleChange, className: "form-control custom-control-input col-3 InventoryDet", name: "", id: "", style: { cursor: 'pointer' } }),
                            React.createElement("label", { htmlFor: "Plan As Per Del", style: { fontSize: "0.8em" }, className: "form-label labl labl2" }, "Plan As Per Del. Date"),
                            React.createElement("input", { type: "checkbox", onBlur: handleChange, className: "form-control custom-control-input col-3 InventoryDet", name: "", id: "", style: { cursor: 'pointer' } }),
                            React.createElement("label", { htmlFor: "Consumption Not", style: { fontSize: "0.8em" }, className: "form-label labl labl2" }, "Consumption Not on Rejection"),
                            React.createElement("input", { type: "checkbox", onBlur: handleChange, className: "form-control custom-control-input col-3 InventoryDet", name: "", id: "", style: { cursor: 'pointer' } }),
                            React.createElement("label", { htmlFor: "Produce Item", style: { fontSize: "0.8em" }, className: "form-label labl labl2" }, "Produce Item As Per Process In Sample Prod"),
                            React.createElement("input", { type: "checkbox", onBlur: handleChange, className: "form-control custom-control-input col-3 InventoryDet", name: "", id: "", style: { cursor: 'pointer' } })),
                        React.createElement("span", { className: "d-flex justify-content-between section2 col-sm-12" },
                            React.createElement("label", { htmlFor: "Electricity Req.", style: { fontSize: "0.8em" }, className: "form-label labl labl2" }, "Electricity Req."),
                            React.createElement("input", { type: "checkbox", onBlur: handleChange, className: "form-control custom-control-input col-3 InventoryDet", name: "", id: "", style: { cursor: 'pointer' } }),
                            React.createElement("label", { htmlFor: "Show in Rejection", style: { fontSize: "0.8em" }, className: "form-label labl labl2" }, "Show in Rejection Details Report"),
                            React.createElement("input", { type: "checkbox", onBlur: handleChange, className: "form-control custom-control-input col-3 InventoryDet", name: "", id: "", style: { cursor: 'pointer' } }),
                            React.createElement("label", { htmlFor: " Enable Operator Details", style: { fontSize: "0.8em" }, className: "form-label labl labl2" }, "Enable Operator Details"),
                            React.createElement("input", { type: "checkbox", onBlur: handleChange, className: "form-control custom-control-input col-3 InventoryDet", name: "", id: "", style: { cursor: 'pointer' } }),
                            React.createElement("label", { htmlFor: "Production With Scan Data", style: { fontSize: "0.8em" }, className: "form-label labl labl2" }, "Production With Scan Data"),
                            React.createElement("input", { type: "checkbox", onBlur: handleChange, className: "form-control custom-control-input col-3 InventoryDet", name: "", id: "", style: { cursor: 'pointer' } })),
                        React.createElement("span", { className: "d-flex justify-content-between section2 col-sm-12" },
                            React.createElement("label", { htmlFor: " Time Slab", style: { fontSize: "0.8em" }, className: "form-label labl labl2" }, "Time Slab Wise Production"),
                            React.createElement("input", { type: "checkbox", onBlur: handleChange, className: "form-control custom-control-input col-3 InventoryDet", name: "", id: "", style: { cursor: 'pointer' } }),
                            React.createElement("label", { htmlFor: "Show in Rejection per.", style: { fontSize: "0.8em" }, className: "form-label labl labl2" }, "Show Rejection % In Production MIS Report"),
                            React.createElement("input", { type: "checkbox", onBlur: handleChange, className: "form-control custom-control-input col-3 InventoryDet", name: "", id: "", style: { cursor: 'pointer' } }),
                            React.createElement("label", { htmlFor: "Tollerance Not Required", style: { fontSize: "0.8em" }, className: "form-label labl labl2" }, "Tollerance Not Required"),
                            React.createElement("input", { type: "checkbox", onBlur: handleChange, className: "form-control custom-control-input col-3 InventoryDet", name: "", id: "", style: { cursor: 'pointer' } }),
                            React.createElement("label", { htmlFor: "Enable Produce Item Serial No.", style: { fontSize: "0.8em" }, className: "form-label labl labl2" }, "Enable Produce Item Serial No."),
                            React.createElement("input", { type: "checkbox", onBlur: handleChange, className: "form-control custom-control-input col-3 InventoryDet", name: "", id: "", style: { cursor: 'pointer' } })),
                        React.createElement("div", { className: "col-4" })))),
            React.createElement("span", { className: "row-content form col-sm-12 pt-0" },
                React.createElement("fieldset", { className: "form-group border p-0" },
                    React.createElement("legend", { className: "px-2", "data-toggle": "collapse", "data-target": "#OverHead", "aria-expanded": "true", "aria-controls": "OverHead", style: { fontSize: "1.1rem", cursor: "pointer" } },
                        React.createElement("svg", { className: "ml-1", style: { width: "15px" }, xmlns: "http://www.w3.org/2000/svg", viewBox: "0 0 448 512" },
                            React.createElement("path", { d: "M384 32H64C28.65 32 0 60.65 0 96v320c0 35.34 28.65 64 64 64h320c35.35 0 64-28.66 64-64V96C448 60.65 419.3 32 384 32zM345.6 232.3l-104 112C237 349.2 230.7 352 224 352s-13.03-2.781-17.59-7.656l-104-112c-6.5-7-8.219-17.19-4.407-25.94C101.8 197.7 110.5 192 120 192h208c9.531 0 18.19 5.656 21.1 14.41C353.8 215.2 352.1 225.3 345.6 232.3z" }))),
                    React.createElement("div", { className: "show", id: "OverHead" },
                        React.createElement("div", { className: "row row-content col-sm-12 addSaleForm container container-fluid container-lg" },
                            React.createElement("div", { className: "card col-sm-6", style: { padding: "0", margin: "0" } },
                                React.createElement("div", { style: {
                                        display: "flex",
                                        justifyContent: "center",
                                        alignItems: "center",
                                        borderBottom: "1px solid grey",
                                        backgroundColor: "#8389d4",
                                        margin: "0",
                                        padding: "0",
                                    } },
                                    React.createElement("span", { className: "card-title", style: { fontSize: "15px", margin: "0", padding: "0" } }, "Process OverHead")),
                                React.createElement("div", { className: "card-body table-responsive", style: { margin: "0", padding: "0" } },
                                    React.createElement("table", { className: "table table-striped table-bordered table-hover table-sm", style: { margin: "0" } },
                                        React.createElement("thead", { className: "thead-light table-secondary text-center" },
                                            React.createElement("tr", null,
                                                React.createElement("th", null, "S. No"),
                                                React.createElement("th", null, "Name"))),
                                        React.createElement("tbody", null,
                                            React.createElement("tr", null,
                                                React.createElement("th", { scope: "row" }, "1"),
                                                React.createElement("td", null,
                                                    " ",
                                                    React.createElement("input", { name: "Name1", className: "form-control inp AccountMaster", type: "text", title: "Enter Name", style: {
                                                            width: "100%",
                                                            margin: "auto",
                                                            height: "25px",
                                                        } }))),
                                            React.createElement("tr", null,
                                                React.createElement("th", { scope: "row" }, "2"),
                                                React.createElement("td", null,
                                                    React.createElement("input", { name: "Name2", className: "form-control inp AccountMaster", type: "text", title: "Enter Name", style: {
                                                            width: "100%",
                                                            margin: "auto",
                                                            height: "25px",
                                                        } }))),
                                            React.createElement("tr", null,
                                                React.createElement("th", { scope: "row" }, "3"),
                                                React.createElement("td", null,
                                                    React.createElement("input", { name: "Name3", className: "form-control inp AccountMaster", type: "text", title: "Enter Name", style: {
                                                            width: "100%",
                                                            margin: "auto",
                                                            height: "25px",
                                                        } }))))))),
                            React.createElement("div", { className: "card col-sm-6 ", style: { padding: "0", margin: "0" } },
                                React.createElement("div", { style: {
                                        display: "flex",
                                        justifyContent: "center",
                                        alignItems: "center",
                                        borderBottom: "1px solid grey",
                                        backgroundColor: "#8389d4",
                                        margin: "0",
                                        padding: "0",
                                    } },
                                    React.createElement("span", { className: "card-title", style: { fontSize: "15px", margin: "0", padding: "0" } }, "Job Worker List")),
                                React.createElement("div", { className: "card-body table-responsive", style: { margin: "0", padding: "0" } },
                                    React.createElement("table", { className: "table table-striped table-bordered table-hover table-sm", style: { margin: "0" } },
                                        React.createElement("thead", { className: "thead-light table-secondary text-center" },
                                            React.createElement("tr", null,
                                                React.createElement("th", null, "S. No"),
                                                React.createElement("th", null, "Name"),
                                                React.createElement("th", null, "Job Work On"))),
                                        React.createElement("tbody", null,
                                            React.createElement("tr", null,
                                                React.createElement("th", { scope: "row" }, "1"),
                                                React.createElement("td", null,
                                                    " ",
                                                    React.createElement("input", { name: "Name1", className: "form-control inp AccountMaster", type: "text", title: "Enter Name", style: {
                                                            width: "100%",
                                                            margin: "auto",
                                                            height: "25px",
                                                        } })),
                                                React.createElement("td", null,
                                                    " ",
                                                    React.createElement("input", { name: "jobWork1", className: "form-control inp AccountMaster", type: "text", title: "Enter job Work", style: {
                                                            width: "100%",
                                                            margin: "auto",
                                                            height: "25px",
                                                        } }))),
                                            React.createElement("tr", null,
                                                React.createElement("th", { scope: "row" }, "2"),
                                                React.createElement("td", null,
                                                    React.createElement("input", { name: "Name2", className: "form-control inp AccountMaster", type: "text", title: "Enter Name", style: {
                                                            width: "100%",
                                                            margin: "auto",
                                                            height: "25px",
                                                        } })),
                                                React.createElement("td", null,
                                                    React.createElement("input", { name: "jobWork2", className: "form-control inp AccountMaster", type: "text", title: "Enter job Work", style: {
                                                            width: "100%",
                                                            margin: "auto",
                                                            height: "25px",
                                                        } }))),
                                            React.createElement("tr", null,
                                                React.createElement("th", { scope: "row" }, "3"),
                                                React.createElement("td", null,
                                                    React.createElement("input", { name: "Name3", className: "form-control inp AccountMaster", type: "text", title: "Enter Name", style: {
                                                            width: "100%",
                                                            margin: "auto",
                                                            height: "25px",
                                                        } })),
                                                React.createElement("td", null,
                                                    React.createElement("input", { name: "jobWork3", className: "form-control inp AccountMaster", type: "text", title: "Enter job Work", style: {
                                                            width: "100%",
                                                            margin: "auto",
                                                            height: "25px",
                                                        } }))))))),
                            React.createElement("div", { className: "card col-sm-6 mt-2", style: { padding: "0", margin: "0" } },
                                React.createElement("div", { style: {
                                        display: "flex",
                                        justifyContent: "center",
                                        alignItems: "center",
                                        borderBottom: "1px solid grey",
                                        backgroundColor: "#8389d4",
                                        margin: "0",
                                        padding: "0",
                                    } },
                                    React.createElement("span", { className: "card-title", style: {
                                            fontSize: "15px",
                                            margin: "0",
                                            padding: "0",
                                            height: "25px",
                                        } },
                                        "Process Operation Details",
                                        " ")),
                                React.createElement("div", { className: "card-body table-responsive", style: { margin: "0", padding: "0" } },
                                    React.createElement("table", { className: "table table-striped table-bordered table-hover table-sm", style: { margin: "0" } },
                                        React.createElement("thead", { className: "thead-light table-secondary text-center" },
                                            React.createElement("tr", null,
                                                React.createElement("th", null, "S. No"),
                                                React.createElement("th", null, "Opeartion"))),
                                        React.createElement("tbody", null,
                                            React.createElement("tr", null,
                                                React.createElement("th", { scope: "row" }, "1"),
                                                React.createElement("td", null,
                                                    " ",
                                                    React.createElement("input", { name: "Operation1", className: "form-control inp AccountMaster", type: "text", title: "Enter Operation", style: {
                                                            width: "100%",
                                                            margin: "auto",
                                                            height: "25px",
                                                        } }))),
                                            React.createElement("tr", null,
                                                React.createElement("th", { scope: "row" }, "2"),
                                                React.createElement("td", null,
                                                    React.createElement("input", { name: "Operation2", className: "form-control inp AccountMaster", type: "text", title: "Enter Operation", style: {
                                                            width: "100%",
                                                            margin: "auto",
                                                            height: "25px",
                                                        } }))),
                                            React.createElement("tr", null,
                                                React.createElement("th", { scope: "row" }, "3"),
                                                React.createElement("td", null,
                                                    React.createElement("input", { name: "Operation3", className: "form-control inp AccountMaster", type: "text", title: "Enter Operation", style: {
                                                            width: "100%",
                                                            margin: "auto",
                                                            height: "25px",
                                                        } })))))))))))),
        React.createElement("div", { className: "btn-group col-12 mt-3", style: {
                display: "flex",
                justifyContent: "flex-end",
                alignItems: "center",
            } },
            React.createElement("button", { type: "button", style: {
                    border: "2px solid #33b5e5",
                    letterSpacing: 3,
                    width: "100px",
                }, className: "btn btn-info pl-0 pr-0" }, "Save"),
            React.createElement("button", { type: "button", style: {
                    border: "2px solid green",
                    letterSpacing: 3,
                    width: "200px",
                }, className: "btn btn-success mr-2 ml-2 pl-0 pr-0 " }, "Save & Submit"),
            React.createElement("button", { type: "button", style: { border: "2px solid red", letterSpacing: 3, width: "100px" }, className: "btn btn-danger pl-0 pr-0" }, "Quit"))));
}
exports.default = Process_Page;
//# sourceMappingURL=process.page.js.map