"use strict";
var __rest = (this && this.__rest) || function (s, e) {
    var t = {};
    for (var p in s) if (Object.prototype.hasOwnProperty.call(s, p) && e.indexOf(p) < 0)
        t[p] = s[p];
    if (s != null && typeof Object.getOwnPropertySymbols === "function")
        for (var i = 0, p = Object.getOwnPropertySymbols(s); i < p.length; i++) {
            if (e.indexOf(p[i]) < 0 && Object.prototype.propertyIsEnumerable.call(s, p[i]))
                t[p[i]] = s[p[i]];
        }
    return t;
};
Object.defineProperty(exports, "__esModule", { value: true });
var React = require("react");
var react_1 = require("react");
var custom_input_component_1 = require("../../components/custom-input/custom-input.component");
var custom_switch_component_1 = require("../../components/CustomSwitch/custom-switch.component");
function Process_Page(_a) {
    var getMasterType = _a.getMasterType, pageTitle = _a.pageTitle, configType = _a.configType, handleChange = _a.handleChange, handlePosting = _a.handlePosting, defaultData = _a.defaultData, otherProps = __rest(_a, ["getMasterType", "pageTitle", "configType", "handleChange", "handlePosting", "defaultData"]);
    var _b = (0, react_1.useState)(false), ToggelValue = _b[0], setToggelValue = _b[1];
    console.log("toggel Value", ToggelValue);
    return (React.createElement(React.Fragment, null,
        React.createElement("div", { className: "main card firstDiv" },
            React.createElement("div", { className: "text-center card-title col-12", style: { textAlign: "start", backgroundColor: "#8389d4" } },
                React.createElement("span", { className: "row-header p-0 m-0" }, pageTitle)),
            React.createElement("form", { className: "row-content form col-sm-12 pt-0" },
                React.createElement(React.Fragment, null,
                    React.createElement("span", { className: "d-flex section2 col-sm-12" },
                        React.createElement(custom_input_component_1.default, { name: "process", classCategory: "form-control inp mb-2 Process", ipType: "text", label: "Process", ipTitle: "Enter Process", dataArray: [] }),
                        React.createElement(custom_input_component_1.default, { name: "processFloor", classCategory: "form-control inp mb-2 ProcessFloor", ipType: "text", label: "Process Floor", ipTitle: "Enter Process Floor", dataArray: [] }),
                        React.createElement(custom_input_component_1.default, { name: "clipBoard", classCategory: "form-control inp mb-2 ClipBoard", ipType: "text", label: "P Srno For ClipBoard", ipTitle: "Enter ClipBoard", dataArray: [] })),
                    React.createElement("span", { className: "d-flex section2 col-sm-12" },
                        React.createElement(custom_input_component_1.default, { name: "debitorAccount", classCategory: "form-control inp mb-2 DebitorAccount", ipType: "text", label: "Debitor Account", ipTitle: "Enter Debitor Account", dataArray: [] }),
                        React.createElement(custom_input_component_1.default, { name: "addJobWork", classCategory: "form-control inp mb-2 AddJobWork", ipType: "text", label: "Add JobWork chrgs.", ipTitle: "Enter Add JobWork chrgs.", dataArray: [] }),
                        React.createElement(custom_input_component_1.default, { name: "tollerance", classCategory: "form-control inp mb-2 Tollerance", ipType: "number", label: "Tollerance (%)", ipTitle: "Enter Tollerance", dataArray: [] })),
                    React.createElement("span", { className: "d-flex section2 col-sm-12" },
                        React.createElement(custom_input_component_1.default, { name: "overHead", classCategory: "form-control inp mb-2 OverHead", ipType: "number", label: "OverHead (%)", ipTitle: "Enter OverHead", dataArray: [] }),
                        React.createElement(custom_input_component_1.default, { name: "Material Req", classCategory: "form-control inp mb-2 MaterialReq", ipType: "text", label: "Material Req. before Days", ipTitle: "Enter Material Req. before Days", dataArray: [] }),
                        React.createElement(custom_input_component_1.default, { name: "Process Group No", classCategory: "form-control inp mb-2 MaterialReq", ipType: "text", label: "Process Group No", ipTitle: "Enter Process Group No", dataArray: [] })),
                    React.createElement("span", { className: "d-flex section2 col-sm-12" },
                        React.createElement(custom_input_component_1.default, { name: "PlanHours", classCategory: "form-control inp mb-2 PlanHours", ipType: "number", label: "Plan Hours Per Day", ipTitle: "Enter Plan Hours Per Day", dataArray: [] }),
                        React.createElement(custom_input_component_1.default, { name: "Before Days", classCategory: "form-control inp mb-2 BeforeDays", ipType: "text", label: "Before Days", ipTitle: "Enter Before Days", dataArray: [] }))),
                React.createElement("div", { className: "col-4" })),
            React.createElement("span", { className: "row-content col-sm-12 pt-0" },
                React.createElement("div", { className: "show", id: "Switch" },
                    React.createElement("span", { className: "d-flex justify-content-between section2 col-sm-12" },
                        React.createElement(React.Fragment, null,
                            React.createElement(custom_switch_component_1.CustomeSwitch2, { lablClass: "custom-control-label col-9", label: "For Job Working", id: "SClsBal", name: "SClsBal", classCat: "form-control custom-control-input col-3 seriesConf", handleChange: handleChange })),
                        React.createElement(React.Fragment, null,
                            React.createElement(custom_switch_component_1.CustomeSwitch2, { lablClass: "custom-control-label col-9", label: "is Accounting Posting", id: "SClsBal", name: "SClsBal", classCat: "form-control custom-control-input col-3 seriesConf", handleChange: handleChange })),
                        React.createElement(React.Fragment, null,
                            React.createElement(custom_switch_component_1.CustomeSwitch2, { lablClass: "custom-control-label col-9", label: "Produce Qty is Greater then Paln Qty", id: "SClsBal", name: "SClsBal", classCat: "form-control custom-control-input col-3 seriesConf", handleChange: handleChange }))),
                    React.createElement("span", { className: "d-flex justify-content-between section2 col-sm-12" },
                        React.createElement(React.Fragment, null,
                            React.createElement(custom_switch_component_1.CustomeSwitch2, { lablClass: "custom-control-label col-9", label: "Change Consume Item Quantity", id: "SClsBal", name: "SClsBal", classCat: "form-control custom-control-input col-3 seriesConf", handleChange: handleChange })),
                        React.createElement(React.Fragment, null,
                            React.createElement(custom_switch_component_1.CustomeSwitch2, { lablClass: "custom-control-label col-9", label: "Is Consume Qty Less than Req. Qty", id: "SClsBal", name: "SClsBal", classCat: "form-control custom-control-input col-3 seriesConf", handleChange: handleChange })),
                        React.createElement(React.Fragment, null,
                            React.createElement(custom_switch_component_1.CustomeSwitch2, { lablClass: "custom-control-label col-9", label: "Is Consume Qty Zero", id: "SClsBal", name: "SClsBal", classCat: "form-control custom-control-input col-3 seriesConf", handleChange: handleChange }))),
                    React.createElement("span", { className: "d-flex justify-content-between section2 col-sm-12" },
                        React.createElement(React.Fragment, null,
                            React.createElement(custom_switch_component_1.CustomeSwitch2, { lablClass: "custom-control-label col-9", label: " Mold Req", id: "SClsBal", name: "SClsBal", classCat: "form-control custom-control-input col-3 seriesConf", handleChange: handleChange })),
                        React.createElement(React.Fragment, null,
                            React.createElement(custom_switch_component_1.CustomeSwitch2, { lablClass: "custom-control-label col-9", label: "Minus Stock Qty in Req.", id: "SClsBal", name: "SClsBal", classCat: "form-control custom-control-input col-3 seriesConf", handleChange: handleChange })),
                        React.createElement(React.Fragment, null,
                            React.createElement(custom_switch_component_1.CustomeSwitch2, { lablClass: "custom-control-label col-9", label: "Add New Cons. Item at Production", id: "SClsBal", name: "SClsBal", classCat: "form-control custom-control-input col-3 seriesConf", handleChange: handleChange }))),
                    React.createElement("span", { className: "d-flex justify-content-between section2 col-sm-12" },
                        React.createElement(React.Fragment, null,
                            React.createElement(custom_switch_component_1.CustomeSwitch2, { lablClass: "custom-control-label col-9", label: "Plan As Per Del. Date", id: "SClsBal", name: "SClsBal", classCat: "form-control custom-control-input col-3 seriesConf", handleChange: handleChange })),
                        React.createElement(React.Fragment, null,
                            React.createElement(custom_switch_component_1.CustomeSwitch2, { lablClass: "custom-control-label col-9", label: "Consumption Not on Rejection", id: "SClsBal", name: "SClsBal", classCat: "form-control custom-control-input col-3 seriesConf", handleChange: handleChange })),
                        React.createElement(React.Fragment, null,
                            React.createElement(custom_switch_component_1.CustomeSwitch2, { lablClass: "custom-control-label col-9", label: "Produce Item As Per Process In Sample Prod", id: "SClsBal", name: "SClsBal", classCat: "form-control custom-control-input col-3 seriesConf", handleChange: handleChange }))),
                    React.createElement("span", { className: "d-flex justify-content-between section2 col-sm-12" },
                        React.createElement(React.Fragment, null,
                            React.createElement(custom_switch_component_1.CustomeSwitch2, { lablClass: "custom-control-label col-9", label: "Electricity Req.", id: "SClsBal", name: "SClsBal", classCat: "form-control custom-control-input col-3 seriesConf", handleChange: handleChange })),
                        React.createElement(React.Fragment, null,
                            React.createElement(custom_switch_component_1.CustomeSwitch2, { lablClass: "custom-control-label col-9", label: " Show in Rejection Details Report", id: "SClsBal", name: "SClsBal", classCat: "form-control custom-control-input col-3 seriesConf", handleChange: handleChange })),
                        React.createElement(React.Fragment, null,
                            React.createElement(custom_switch_component_1.CustomeSwitch2, { lablClass: "custom-control-label col-9", label: " Enable Operator Details", id: "SClsBal", name: "SClsBal", classCat: "form-control custom-control-input col-3 seriesConf", handleChange: handleChange }))),
                    React.createElement("span", { className: "d-flex justify-content-between section2 col-sm-12" },
                        React.createElement(React.Fragment, null,
                            React.createElement(custom_switch_component_1.CustomeSwitch2, { lablClass: "custom-control-label col-9", label: " Production With Scan Data", id: "SClsBal", name: "SClsBal", classCat: "form-control custom-control-input col-3 seriesConf", handleChange: handleChange })),
                        React.createElement(React.Fragment, null,
                            React.createElement(custom_switch_component_1.CustomeSwitch2, { lablClass: "custom-control-label col-9", label: " Time Slab Wise Production", id: "SClsBal", name: "SClsBal", classCat: "form-control custom-control-input col-3 seriesConf", handleChange: handleChange })),
                        React.createElement(React.Fragment, null,
                            React.createElement(custom_switch_component_1.CustomeSwitch2, { lablClass: "custom-control-label col-9", label: "Show Rejection % In Production MIS Report", id: "SClsBal", name: "SClsBal", classCat: "form-control custom-control-input col-3 seriesConf", handleChange: handleChange }))),
                    React.createElement("span", { className: "d-flex justify-content-between section2 col-sm-12" },
                        React.createElement(React.Fragment, null,
                            React.createElement(custom_switch_component_1.CustomeSwitch2, { lablClass: "custom-control-label col-9", label: " Tollerance Not Required", id: "SClsBal", name: "SClsBal", classCat: "form-control custom-control-input col-3 seriesConf", handleChange: handleChange })),
                        React.createElement(React.Fragment, null,
                            React.createElement(custom_switch_component_1.CustomeSwitch2, { lablClass: "custom-control-label col-9", label: " Enable Produce Item Serial No.", id: "SClsBal", name: "SClsBal", classCat: "form-control custom-control-input col-3 seriesConf", handleChange: handleChange })),
                        React.createElement("div", { className: "col-4" })))),
            React.createElement("hr", null),
            React.createElement("span", { className: "row-content form col-sm-12 pt-0" },
                React.createElement("div", { className: "show collapse", id: "OverHead" },
                    React.createElement("div", { className: "row row-content col-sm-12 addSaleForm container container-fluid container-lg" },
                        React.createElement("div", { className: "card col-sm-6", style: { padding: "0", margin: "0" } },
                            React.createElement("div", { style: {
                                    display: "flex",
                                    justifyContent: "center",
                                    alignItems: "center",
                                    borderBottom: "1px solid grey",
                                    backgroundColor: "#8389d4",
                                    margin: "0",
                                    padding: "0",
                                } },
                                React.createElement("span", { className: "card-title", style: { fontSize: "15px", margin: "0", padding: "0" } }, "Process OverHead")),
                            React.createElement("div", { className: "card-body table-responsive", style: { margin: "0", padding: "0" } },
                                React.createElement("table", { className: "table table-striped table-bordered table-hover table-sm", style: { margin: "0" } },
                                    React.createElement("thead", { className: "thead-light table-secondary text-center" },
                                        React.createElement("tr", null,
                                            React.createElement("th", null, "S. No"),
                                            React.createElement("th", null, "Name"))),
                                    React.createElement("tbody", null,
                                        React.createElement("tr", null,
                                            React.createElement("th", { scope: "row" }, "1"),
                                            React.createElement("td", null,
                                                " ",
                                                React.createElement("input", { name: "Name1", className: "form-control inp AccountMaster", type: "text", title: "Enter Name", style: {
                                                        width: "100%",
                                                        margin: "auto",
                                                        height: "25px",
                                                    } }))),
                                        React.createElement("tr", null,
                                            React.createElement("th", { scope: "row" }, "2"),
                                            React.createElement("td", null,
                                                React.createElement("input", { name: "Name2", className: "form-control inp AccountMaster", type: "text", title: "Enter Name", style: {
                                                        width: "100%",
                                                        margin: "auto",
                                                        height: "25px",
                                                    } }))),
                                        React.createElement("tr", null,
                                            React.createElement("th", { scope: "row" }, "3"),
                                            React.createElement("td", null,
                                                React.createElement("input", { name: "Name3", className: "form-control inp AccountMaster", type: "text", title: "Enter Name", style: {
                                                        width: "100%",
                                                        margin: "auto",
                                                        height: "25px",
                                                    } }))))))),
                        React.createElement("div", { className: "card col-sm-6 ", style: { padding: "0", margin: "0" } },
                            React.createElement("div", { style: {
                                    display: "flex",
                                    justifyContent: "center",
                                    alignItems: "center",
                                    borderBottom: "1px solid grey",
                                    backgroundColor: "#8389d4",
                                    margin: "0",
                                    padding: "0",
                                } },
                                React.createElement("span", { className: "card-title", style: { fontSize: "15px", margin: "0", padding: "0" } }, "Job Worker List")),
                            React.createElement("div", { className: "card-body table-responsive", style: { margin: "0", padding: "0" } },
                                React.createElement("table", { className: "table table-striped table-bordered table-hover table-sm", style: { margin: "0" } },
                                    React.createElement("thead", { className: "thead-light table-secondary text-center" },
                                        React.createElement("tr", null,
                                            React.createElement("th", null, "S. No"),
                                            React.createElement("th", null, "Name"),
                                            React.createElement("th", null, "Job Work On"))),
                                    React.createElement("tbody", null,
                                        React.createElement("tr", null,
                                            React.createElement("th", { scope: "row" }, "1"),
                                            React.createElement("td", null,
                                                " ",
                                                React.createElement("input", { name: "Name1", className: "form-control inp AccountMaster", type: "text", title: "Enter Name", style: {
                                                        width: "100%",
                                                        margin: "auto",
                                                        height: "25px",
                                                    } })),
                                            React.createElement("td", null,
                                                " ",
                                                React.createElement("input", { name: "jobWork1", className: "form-control inp AccountMaster", type: "text", title: "Enter job Work", style: {
                                                        width: "100%",
                                                        margin: "auto",
                                                        height: "25px",
                                                    } }))),
                                        React.createElement("tr", null,
                                            React.createElement("th", { scope: "row" }, "2"),
                                            React.createElement("td", null,
                                                React.createElement("input", { name: "Name2", className: "form-control inp AccountMaster", type: "text", title: "Enter Name", style: {
                                                        width: "100%",
                                                        margin: "auto",
                                                        height: "25px",
                                                    } })),
                                            React.createElement("td", null,
                                                React.createElement("input", { name: "jobWork2", className: "form-control inp AccountMaster", type: "text", title: "Enter job Work", style: {
                                                        width: "100%",
                                                        margin: "auto",
                                                        height: "25px",
                                                    } }))),
                                        React.createElement("tr", null,
                                            React.createElement("th", { scope: "row" }, "3"),
                                            React.createElement("td", null,
                                                React.createElement("input", { name: "Name3", className: "form-control inp AccountMaster", type: "text", title: "Enter Name", style: {
                                                        width: "100%",
                                                        margin: "auto",
                                                        height: "25px",
                                                    } })),
                                            React.createElement("td", null,
                                                React.createElement("input", { name: "jobWork3", className: "form-control inp AccountMaster", type: "text", title: "Enter job Work", style: {
                                                        width: "100%",
                                                        margin: "auto",
                                                        height: "25px",
                                                    } }))))))),
                        React.createElement("div", { className: "card col-sm-6 mt-2", style: { padding: "0", margin: "0" } },
                            React.createElement("div", { style: {
                                    display: "flex",
                                    justifyContent: "center",
                                    alignItems: "center",
                                    borderBottom: "1px solid grey",
                                    backgroundColor: "#8389d4",
                                    margin: "0",
                                    padding: "0",
                                } },
                                React.createElement("span", { className: "card-title", style: {
                                        fontSize: "15px",
                                        margin: "0",
                                        padding: "0",
                                        height: "25px",
                                    } },
                                    "Process Operation Details",
                                    " ")),
                            React.createElement("div", { className: "card-body table-responsive", style: { margin: "0", padding: "0" } },
                                React.createElement("table", { className: "table table-striped table-bordered table-hover table-sm", style: { margin: "0" } },
                                    React.createElement("thead", { className: "thead-light table-secondary text-center" },
                                        React.createElement("tr", null,
                                            React.createElement("th", null, "S. No"),
                                            React.createElement("th", null, "Opeartion"))),
                                    React.createElement("tbody", null,
                                        React.createElement("tr", null,
                                            React.createElement("th", { scope: "row" }, "1"),
                                            React.createElement("td", null,
                                                " ",
                                                React.createElement("input", { name: "Operation1", className: "form-control inp AccountMaster", type: "text", title: "Enter Operation", style: {
                                                        width: "100%",
                                                        margin: "auto",
                                                        height: "25px",
                                                    } }))),
                                        React.createElement("tr", null,
                                            React.createElement("th", { scope: "row" }, "2"),
                                            React.createElement("td", null,
                                                React.createElement("input", { name: "Operation2", className: "form-control inp AccountMaster", type: "text", title: "Enter Operation", style: {
                                                        width: "100%",
                                                        margin: "auto",
                                                        height: "25px",
                                                    } }))),
                                        React.createElement("tr", null,
                                            React.createElement("th", { scope: "row" }, "3"),
                                            React.createElement("td", null,
                                                React.createElement("input", { name: "Operation3", className: "form-control inp AccountMaster", type: "text", title: "Enter Operation", style: {
                                                        width: "100%",
                                                        margin: "auto",
                                                        height: "25px",
                                                    } }))))))))))),
        React.createElement("div", { className: "btn-group col-12 mt-3", style: {
                display: "flex",
                justifyContent: "flex-end",
                alignItems: "center",
            } },
            React.createElement("button", { type: "button", style: {
                    border: "2px solid #33b5e5",
                    letterSpacing: 3,
                    width: "100px",
                }, className: "btn btn-info pl-0 pr-0" }, "Save"),
            React.createElement("button", { type: "button", style: {
                    border: "2px solid green",
                    letterSpacing: 3,
                    width: "200px",
                }, className: "btn btn-success mr-2 ml-2 pl-0 pr-0 " }, "Save & Submit"),
            React.createElement("button", { type: "button", style: { border: "2px solid red", letterSpacing: 3, width: "100px" }, className: "btn btn-danger pl-0 pr-0" }, "Quit"))));
}
exports.default = Process_Page;
//# sourceMappingURL=process.page.js.map